takdhum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tdlogin/', admin.site.urls),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quizs.urls')),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('course/<category>', views.courseCategory, name='single_category'),
    path('course/<category>/<level>', views.drawing_course, name='drawing_course'),
    path('<category>/course/<course>', views.course, name='single_course'),
    path('all-courses', views.all_course, name='all_course'),
    path('popular-courses', views.popular_course, name='popular_course'),
    path('resent-courses', views.recent_course, name='recent_course'),
    path('event/<event_id>', views.event, name='single_event_page'),
    path('contact', views.contact, name='contact_page'),
    path('about-us', views.about_us, name='about_page'),
    path('faq', views.faq, name='faq_page'),
    path('login', views.get_login, name='get_login'),
    path('logout', views.get_logout, name='logout'),
    path('profile/<username>/', views.get_user_profile, name='user_profile'),
    path('sign-up', views.signup, name='sign-up'),
    path('user-message', views.user_message, name='user_message'),
    # path('activate/<uidb64>/<token>', views.activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
     views.activate, name='activate'),
    # path('profile/<slug:slug>/', views.ProfilePage.as_view(), name='user_profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('events_list', views.EventListView.as_view(), name='event_list'),
    path('subcriber', views.subscriber, name='subcriber'),
    path('search', views.search, name='search'),
    path('<user>/my-course/', views.my_course, name='my_course'),
    # path('<user>/my-course/', views.TakenCourseList.as_view(), name='my_course')
    path('<user>/delete_course/<int:pk>/', views.taken_course_delete, name='delete_course'),
    # path('taken-quiz/<int:pk>/', views.take_quiz, name='take-quiz'),
    path('<course>/question-list/', views.question_list, name='question-list'),
    path('question/', views.take_quiz, name='question'),
    path('student-answer/<username>/', views.student_answer, name='student-answer'),
    path('mcq/<int:question_id>/', views.score, name='vote'),
    path('all-answer/', views.AllAnswer.as_view(), name="all-answer"),
    path('quize-datails/', views.quize_details, name='quize-details'),
    path('vedio_link/', views.vedio_link, name='vedio_link'),
    path('<category>/<course>/<video>/', views.single_video, name='single_vedio'),
    path('<course_watch>/watch_vedio/', views.watch_vedio, name='watch_vedio'),
    # path('api/status/', views.api_status, name='api-status'),
]

web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    profile_picture = models.ImageField(upload_to='Profile_picture/', null=True, blank=True)
    father_name = models.CharField(max_length=255, blank=True, null=True)
    mother_name = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.IntegerField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    institute = models.CharField(max_length=255, blank=True, null=True)
    facebook = models.CharField(max_length=255, blank=True, null=True)
    twitter = models.CharField(max_length=255, blank=True, null=True)
    youtube = models.CharField(max_length=255, blank=True, null=True)
    linkedin = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    def get_absulete_url(self):
        return reverse('user_profile', args=[str(self.slug)])


@receiver(post_save, sender=User)
def create_profile_for_user(sender, instance=None, created=False, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


class CourseCategory(models.Model):
    category_name = models.CharField(max_length=50)
    category_url = models.CharField(max_length=50)
    thumbnail_image = models.ImageField(upload_to='Course_Category', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.category_name


class CourseLevel(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Course(models.Model):
    course_title = models.CharField(max_length=150)
    course_url = models.CharField(max_length=150)
    thumbnail_image = models.ImageField(upload_to='Courses')
    course_category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)
    course_level = models.ForeignKey(CourseLevel, null=True, blank=True, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.course_title


class TakenCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='taken_courses')
    taken_course_title = models.CharField(max_length=255, null=True)
    taken_course_url = models.CharField(max_length=255, null=True)
    taken_course_image = models.ImageField(upload_to='User/TakenCourses', null=True)
    taken_course_category = models.CharField(max_length=255, null=True)
    taken_category_url = models.CharField(max_length=255, null=True)
    view = models.PositiveIntegerField(blank=True, null=True)
    taken_time = models.DateTimeField(auto_now=True)
    last_visited = models.DateTimeField()

    class Meta:
        unique_together = (('user', 'taken_course_url'),)

    def get_absolute_url(self):
        return reverse('my_course', kwargs={'pk': self.pk})

    def __str__(self):
        return self.taken_course_url


class SingleVideo(models.Model):
    video_title = models.CharField(max_length=150)
    video_url = models.CharField(max_length=150)
    video_link = models.URLField()
    course_name = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.video_title


class AboutUs(models.Model):
    our_journey = models.TextField()
    our_history_and_passions = models.TextField(blank=True, null=True)
    about_image = models.ImageField(upload_to='About us')

    def __str__(self):
        return self.our_journey


class Basic_info(models.Model):
    name = models.CharField(max_length=100)
    slogan = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='About us')
    phone_1 = models.CharField(max_length=15)
    phone_2 = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField()
    office_address = models.TextField()
    promo_video = models.URLField(blank=True, null=True)
    google_map_link = models.URLField(null=True, blank=True)
    facebook_link = models.URLField(null=True, blank=True)
    google_plus_link = models.URLField(null=True, blank=True)
    youtube_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Slider(models.Model):
    small_text = models.CharField(max_length=100, null=True, blank=True)
    big_text = models.CharField(max_length=100)
    paragraph = models.CharField(max_length=250)
    slide_image = models.ImageField(upload_to='Slider_Image')

    def __str__(self):
        return self.big_text


class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    date_and_time = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.question


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.CharField(max_length=3)
    month = models.CharField(max_length=10)
    start_and_end_time = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    image = models.ImageField(upload_to='Events')
    gallery_image1 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image2 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image3 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image4 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image5 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image6 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image7 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image8 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image9 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image10 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image11 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image12 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    Image = models.ImageField(upload_to='Projects')
    upload_time = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_time = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    person_name = models.CharField(max_length=100)
    person_designation = models.CharField(max_length=100)
    person_comment = models.TextField()
    person_image = models.ImageField(upload_to='Testimonial')
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.person_name


class UserMessage(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.first_name + self.last_name


class Subcribe(models.Model):
    subcriber_email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subcriber_email


class Question(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    question = models.CharField('Question', max_length=400)
    question_file = models.FileField('Question', upload_to='Question-file', blank=True, null=True)
    option1 = models.CharField(max_length=50, blank=True, null=True)
    option2 = models.CharField(max_length=50, blank=True, null=True)
    option3 = models.CharField(max_length=50, blank=True, null=True)
    option4 = models.CharField(max_length=50, blank=True, null=True)
    correct_answer = models.CharField(max_length=25, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.question


class StudentAnswer(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    answer_file = models.FileField(upload_to='Student-answer', blank=True, null=True)
    answer_text = models.CharField(max_length=255, blank=True, null=True)
    counter = models.PositiveIntegerField(blank=True, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    is_pass = models.BooleanField(default=False)

    def __str__(self):
        return self.student.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='taken_quizzes')
    date = models.DateTimeField(auto_now_add=True)


class WatchVideo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)

web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from web.models import Profile, UserMessage, Subcribe, Question, StudentAnswer


class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control", 'placeholder':"UserID", 'value':""}))
    email = forms.EmailField(max_length=200, help_text='Required', widget=forms.TextInput(attrs={'class':"form-control", 'placeholder':"e-mail", 'value':""}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password', 'value':''}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password', 'value':''}))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserMessageForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.Textarea()


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'col-sm-6'


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('slug', 'user')


class ContactForm(forms.ModelForm):

    class Meta:
        model = UserMessage
        fields = '__all__'


class SubcriberForm(forms.ModelForm):

    class Meta:
        model = Subcribe
        fields = '__all__'


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('option1', 'option2', 'option3', 'option4')


class AnswerForm(forms.ModelForm):

    class Meta:
        model = StudentAnswer
        fields = ('answer_file',)

web/templates/takdhum/profile/my_course.html
{% extends 'takdhum/profile/base_profile.html' %}

{% block profile_info %}
    <div class="uv-student-courses-overview">
        <h3>COURSES</h3>
        <ul>
            {% if user_course_list %}
                {% for course_list in user_course_list %}
                    <li>
                        <div class="row">
                            <div class="col-sm-4">
                                <a href="{% url 'single_course' category=course_list.taken_category_url course=course_list.taken_course_url %}">
                                    <div class="course-feature-img">
                                        <img src="{{ course_list.taken_course_image.url }}" alt=""
                                             class="img-responsive">
                                    </div>
                                </a>
                            </div>
                            <div class="col-sm-8">
                                <div class="uv-std-course-info">
                                    <a href="{% url 'single_course' category=course_list.taken_category_url course=course_list.taken_course_url %}">
                                        <h4>{{ course_list.taken_course_title }}</h4></a>
                                    <span><small>Course Category - <a
                                            href="{% url 'single_category' category=course_list.taken_category_url %}"> {{ course_list.taken_course_category }}</a></small></span>
                                    <br/><span><small>Course Taken: {{ course_list.taken_time|timesince }} ago</small></span>
                                    {% if course_list.watch_video.first %}
                                    <h4>Watch Video:</h4>
                                        <p>{{ course_list.watch_video.first }}</p>
                                        <a href="{% url 'watch_vedio' course_watch=course_list.taken_course_url %}">view all</a>

{#                                    {% for vedio in watch_video %}#}
{#                                        {{ vedio.vedio }}#}
{#                                        {% endfor %}#}
{#                                    <br/><span><small>Last visited: {{ course_list.last_visited|timesince }} ago</small></span>#}
                                    {% endif %}
                                    <br/><br/><a href="{% url 'delete_course' user=request.user pk=course_list.pk %}" class="btn btn-danger view-full-event"> Remove</a>
{#                                    <div class="uv-std-course-review">#}
                                        <!--
                                        <ul>
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                            <li><i class="fa fa-star"></i></li>
                                        </ul>
                                        -->
{#                                    </div>#}
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            {% else %}
                <h4>OOh! You don't take any course yet.</h4>
                <h4>Take a course now <a href="{% url 'all_course' %}" class="btn btn-base view-full-event"> View
                    Course</a></h4>

            {% endif %}
        </ul>
    </div>
{% endblock %}

web/templates/takdhum/profile/my_taken_course.html
{% extends 'takdhum/profile/base_profile.html' %}

{% block profile_info %}

    <div class="uv-student-courses-overview">
        <h3>Taken Quiz : Course name</h3>
        <ul>
            {% for answer in studentanswer_list %}
                <li>
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="uv-std-course-info">
                                <form class="form" action="{% url 'quize-details' %}" method="post" >{% csrf_token %}
                                    <button class="btn btn-outline-success" type="submit" name="q" value="{{ answer }}">{{ answer }}</button>
                                </form>
{#                                <p><span class="text-danger">Question :</span> {{ answer.question }}</p>#}
{#                                <h6><span class="text-success">Answer : </span></h6>#}
{#                                {% if answer.answer_file %}#}
{#                                    <img src="{{ answer.answer_file.url }}" alt="" class="img-responsive">#}
{#                                    {% if answer.is_pass %}#}
{#                                        <h6><span class="text-success">Comment : </span></h6>#}
{#                                        <p>Congrates,You got Pass</p>#}
{#                                    {% endif %}#}
{#                                {% endif %}#}
{#                                {% if answer.answer_text %}#}
{#                                    <p>{{ answer.answer_text }}</p>#}
{#                                    {% if answer.is_pass %}#}
{#                                        <h6><span class="text-success">Comment : </span></h6>#}
{#                                        <p>Congrates,You got Pass</p>#}
{#                                    {% endif %}#}
{#                                {% endif %}#}
{#                                <hr>#}
                                {#                                   <br/><span><small>Last visited: {{ course_list.last_visited|timesince }} ago</small></span>#}
                            </div>
                        </div>
                    </div>
                </li>
            {% empty %}
                <h4>OOh! You don't take any Quiz yet.</h4>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

web/templates/takdhum/profile/profile_settings.html
{% extends 'takdhum/profile/base_profile.html' %}
{% load crispy_forms_tags %}
{% block profile_info %}
    <div class="uv-student-courses-overview">
        <h3>Profile Setting</h3>

        <div class="uv-profile-setting-inner">

            <form class="uv-profile-setting-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
                <div class="col-xs-12">
                    <input type="submit" value="Update Profile" class="btn btn-fill">
                </div>
            </form>


            <!--
                                    <form class="uv-profile-setting-form" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="form-group col-sm-6">
                                                <input type="text" value="{{ user.first_name }}" name="first_name" id="id_first_name" placeholder="First/Last Name" class="form-control"/>
                                            </div>
                                            <div class="form-group col-sm-6">
                                                <input type="text" name="last_name" value="{{ user.last_name }}" id="id_last_name" placeholder="Profile/username" class="form-control"/>
                                            </div>
                                            <div class="form-group col-sm-6">
                                                <input type="email" name="email" id="id_email" value="{{ user.email }}" placeholder="Email" class="form-control"/>
                                            </div>
                                            <div class="form-group col-sm-6">
                                                <input type="text" name="phone_number" value="{{ user.profile.phone_number }}" placeholder="Phone" class="form-control"/>
                                            </div>
                                            <div class="form-group col-sm-6">
                                                <input type="text" name="" value="{{ user.profile.institute}}" placeholder="Institute" class="form-control"/>
                                            </div>
                                            <div class="form-group col-xs-12">
                                                <input name="" id="" class="form-control" value="{{ user.profile.address }}" placeholder="About You" cols="30" rows="6"/>
                                            </div>
                                            <hr>
                                            <div class="clearfix"></div>
                                            <div class="col-md-5 col-sm-12">
                                                <h3>UPLOAD PHOTO</h3>
                                            </div>
                                            <div class="col-md-7 col-sm-12">
                                                <h3>OTHER PHOTOS</h3>
                                                <a href="#" class="btn btn-fill margin-b-15">Choose Photo</a>
                                                <ul class="uv-choose-photo">
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/android_4.jpg" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/ios_4.jpg" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/javascript_4.png" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/laravel_4.png" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/photography_4.jpg" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/team_4.jpg" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/wordpress_4.jpg" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/x-logo_4.png" alt="" class="img-responsive"></li>
                                                    <li class="col-md-4 col-sm-6"><img src="assets/images/b1.jpg" alt="" class="img-responsive"></li>
                                                </ul>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="uv-social-setting">
                                                <h3 class="margin-b-15 col-xs-12">Social: </h3>

                                                <div class="form-group col-sm-6">
                                                    <input type="text" value="{{ user.profile.facebook }}" name="" placeholder="Facebook" class="form-control"/>
                                                </div>
                                                <div class="form-group col-sm-6">
                                                    <input type="text" name="" value="{{ user.profile.twitter }}" placeholder="Twitter" class="form-control"/>
                                                </div>
                                                <div class="form-group col-sm-6">
                                                    <input type="text" name="" value="{{ user.profile.linkedin }}" placeholder="Linkinin" class="form-control"/>
                                                </div>
                                            </div>
                                            <div class="col-xs-12">
                                                <input type="submit" value="Update Profile" class="btn btn-fill">
                                            </div>
                                        </div>
                                    </form>
                                    -->
        </div>
    </div>
{% endblock %}

web/templates/takdhum/profile/quize_details.html
{% extends 'takdhum/profile/base_profile.html' %}

{% block profile_info %}

    <div class="uv-student-courses-overview">
        <h3>{{ course }}</h3>
        <ul>
                <li>
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="uv-std-course-info">
                                <h6>Total Questions: {{ question }}</h6>
                                <h6>Question Answered: {{ answer }}</h6>
                                <h6>Your Score: {{ score }}</h6>
                            </div>
                        </div>
                    </div>
                </li>
        </ul>
    </div>

{% endblock %}

web/templates/takdhum/profile/user_profile.html
{% extends 'takdhum/profile/base_profile.html' %}
{% load crispy_forms_tags %}
{% block profile_info %}
    <div class="uv-student-profile-details-header">
                        <div class="col-md-4 col-sm-12">
                            <div class="uv-student-img">
                                {% if user.profile.profile_picture %}
                                <img src="{{ user.profile.profile_picture.url }}" alt="" class="img-responsive">
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-md-8 col-sm-12">
                            <div class="uv-student-profile-inner">
                                <ul>
                                    <li>
                                        <span>Name:</span>
                                        <p>{{ user.get_full_name }}</p>
                                    </li>
                                    <li>
                                        <span>Student ID:</span>
                                        <p>1000{{ user.id }}</p>
                                    </li>
                                    <li>
                                        <span>Father Name:</span>
                                        <p>{{ user.profile.father_name }}</p>
                                    </li>
                                    <li>
                                        <span>Mother Name:</span>
                                        <p>{{ user.profile.mother_name }}</p>
                                    </li>

                                    <li>
                                        <span>Phone No:</span>
                                        <p>{{ user.profile.phone_number }}</p>
                                    </li>
                                    <li>
                                        <span>Email Address:</span>
                                        <p>{{ user.email}}</p>
                                    </li>
                                    <li>
                                        <span>Institute:</span>
                                        <p>{{ user.profile.institute }}</p>
                                    </li>
                                    <li>
                                        <span>Address:</span>
                                        <p>{{ user.profile.address }}</p>
                                    </li>
                                    <li>
                                        <span>Facebook ID:</span>
                                        <p>{{ user.profile.facebook }}</p>
                                    </li>
                                    <li>
                                        <span>Twitter ID:</span>
                                        <p>{{ user.profile.twitter }}</p>
                                    </li>
                                    <li>
                                        <span>LinkedIn ID:</span>
                                        <p>{{ user.profile.linkedin }}</p>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>

{% endblock %}