takdhum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tdlogin/', admin.site.urls),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quizs.urls')),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('course/<category>', views.courseCategory, name='single_category'),
    path('course/<category>/<level>', views.drawing_course, name='drawing_course'),
    path('<category>/course/<course>', views.course, name='single_course'),
    path('all-courses', views.all_course, name='all_course'),
    path('popular-courses', views.popular_course, name='popular_course'),
    path('resent-courses', views.recent_course, name='recent_course'),
    path('event/<event_id>', views.event, name='single_event_page'),
    path('contact', views.contact, name='contact_page'),
    path('about-us', views.about_us, name='about_page'),
    path('faq', views.faq, name='faq_page'),
    path('login', views.get_login, name='get_login'),
    path('logout', views.get_logout, name='logout'),
    path('profile/<username>/', views.get_user_profile, name='user_profile'),
    path('sign-up', views.signup, name='sign-up'),
    path('user-message', views.user_message, name='user_message'),
    # path('activate/<uidb64>/<token>', views.activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
     views.activate, name='activate'),
    # path('profile/<slug:slug>/', views.ProfilePage.as_view(), name='user_profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('events_list', views.EventListView.as_view(), name='event_list'),
    path('subcriber', views.subscriber, name='subcriber'),
    path('search', views.search, name='search'),
    path('<user>/my-course/', views.my_course, name='my_course'),
    # path('<user>/my-course/', views.TakenCourseList.as_view(), name='my_course')
    path('<user>/delete_course/<int:pk>/', views.taken_course_delete, name='delete_course'),
    # path('taken-quiz/<int:pk>/', views.take_quiz, name='take-quiz'),
    path('<course>/question-list/', views.question_list, name='question-list'),
    path('question/', views.take_quiz, name='question'),
    path('student-answer/<username>/', views.student_answer, name='student-answer'),
    path('mcq/<int:question_id>/', views.score, name='vote'),
    path('all-answer/', views.AllAnswer.as_view(), name="all-answer"),
    path('quize-datails/', views.quize_details, name='quize-details'),
    path('vedio_link/', views.vedio_link, name='vedio_link'),
    path('<category>/<course>/<video>/', views.single_video, name='single_vedio'),
    path('<course_watch>/watch_vedio/', views.watch_vedio, name='watch_vedio'),
    # path('api/status/', views.api_status, name='api-status'),
]

web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    profile_picture = models.ImageField(upload_to='Profile_picture/', null=True, blank=True)
    father_name = models.CharField(max_length=255, blank=True, null=True)
    mother_name = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.IntegerField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    institute = models.CharField(max_length=255, blank=True, null=True)
    facebook = models.CharField(max_length=255, blank=True, null=True)
    twitter = models.CharField(max_length=255, blank=True, null=True)
    youtube = models.CharField(max_length=255, blank=True, null=True)
    linkedin = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    def get_absulete_url(self):
        return reverse('user_profile', args=[str(self.slug)])


@receiver(post_save, sender=User)
def create_profile_for_user(sender, instance=None, created=False, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


class CourseCategory(models.Model):
    category_name = models.CharField(max_length=50)
    category_url = models.CharField(max_length=50)
    thumbnail_image = models.ImageField(upload_to='Course_Category', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.category_name


class CourseLevel(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Course(models.Model):
    course_title = models.CharField(max_length=150)
    course_url = models.CharField(max_length=150)
    thumbnail_image = models.ImageField(upload_to='Courses')
    course_category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)
    course_level = models.ForeignKey(CourseLevel, null=True, blank=True, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.course_title


class TakenCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='taken_courses')
    taken_course_title = models.CharField(max_length=255, null=True)
    taken_course_url = models.CharField(max_length=255, null=True)
    taken_course_image = models.ImageField(upload_to='User/TakenCourses', null=True)
    taken_course_category = models.CharField(max_length=255, null=True)
    taken_category_url = models.CharField(max_length=255, null=True)
    view = models.PositiveIntegerField(blank=True, null=True)
    taken_time = models.DateTimeField(auto_now=True)
    last_visited = models.DateTimeField()

    class Meta:
        unique_together = (('user', 'taken_course_url'),)

    def get_absolute_url(self):
        return reverse('my_course', kwargs={'pk': self.pk})

    def __str__(self):
        return self.taken_course_url


class SingleVideo(models.Model):
    video_title = models.CharField(max_length=150)
    video_url = models.CharField(max_length=150)
    video_link = models.URLField()
    course_name = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.video_title


class AboutUs(models.Model):
    our_journey = models.TextField()
    our_history_and_passions = models.TextField(blank=True, null=True)
    about_image = models.ImageField(upload_to='About us')

    def __str__(self):
        return self.our_journey


class Basic_info(models.Model):
    name = models.CharField(max_length=100)
    slogan = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='About us')
    phone_1 = models.CharField(max_length=15)
    phone_2 = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField()
    office_address = models.TextField()
    promo_video = models.URLField(blank=True, null=True)
    google_map_link = models.URLField(null=True, blank=True)
    facebook_link = models.URLField(null=True, blank=True)
    google_plus_link = models.URLField(null=True, blank=True)
    youtube_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Slider(models.Model):
    small_text = models.CharField(max_length=100, null=True, blank=True)
    big_text = models.CharField(max_length=100)
    paragraph = models.CharField(max_length=250)
    slide_image = models.ImageField(upload_to='Slider_Image')

    def __str__(self):
        return self.big_text


class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    date_and_time = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.question


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.CharField(max_length=3)
    month = models.CharField(max_length=10)
    start_and_end_time = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    image = models.ImageField(upload_to='Events')
    gallery_image1 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image2 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image3 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image4 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image5 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image6 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image7 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image8 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image9 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image10 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image11 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image12 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    Image = models.ImageField(upload_to='Projects')
    upload_time = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_time = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    person_name = models.CharField(max_length=100)
    person_designation = models.CharField(max_length=100)
    person_comment = models.TextField()
    person_image = models.ImageField(upload_to='Testimonial')
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.person_name


class UserMessage(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.first_name + self.last_name


class Subcribe(models.Model):
    subcriber_email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subcriber_email


class Question(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    question = models.CharField('Question', max_length=400)
    question_file = models.FileField('Question', upload_to='Question-file', blank=True, null=True)
    option1 = models.CharField(max_length=50, blank=True, null=True)
    option2 = models.CharField(max_length=50, blank=True, null=True)
    option3 = models.CharField(max_length=50, blank=True, null=True)
    option4 = models.CharField(max_length=50, blank=True, null=True)
    correct_answer = models.CharField(max_length=25, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.question


class StudentAnswer(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    answer_file = models.FileField(upload_to='Student-answer', blank=True, null=True)
    answer_text = models.CharField(max_length=255, blank=True, null=True)
    counter = models.PositiveIntegerField(blank=True, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    is_pass = models.BooleanField(default=False)

    def __str__(self):
        return self.student.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='taken_quizzes')
    date = models.DateTimeField(auto_now_add=True)


class WatchVideo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)

web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from web.models import Profile, UserMessage, Subcribe, Question, StudentAnswer


class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':"form-control", 'placeholder':"UserID", 'value':""}))
    email = forms.EmailField(max_length=200, help_text='Required', widget=forms.TextInput(attrs={'class':"form-control", 'placeholder':"e-mail", 'value':""}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password', 'value':''}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password', 'value':''}))
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserMessageForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.Textarea()


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'col-sm-6'


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('slug', 'user')


class ContactForm(forms.ModelForm):

    class Meta:
        model = UserMessage
        fields = '__all__'


class SubcriberForm(forms.ModelForm):

    class Meta:
        model = Subcribe
        fields = '__all__'


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('option1', 'option2', 'option3', 'option4')


class AnswerForm(forms.ModelForm):

    class Meta:
        model = StudentAnswer
        fields = ('answer_file',)

web/templates/takdhum/about_us.html
{% extends 'takdhum/html/base.html' %}
{% load staticfiles %}

{% block title %} About Us {% endblock title %}
{% block meta %}
<!-- Meta -->
<meta charset="utf-8">
<meta name="description" content="{{ about.our_journey }}" />
<meta name="keywords" content="About Us Takdhum Online Art School in Bangladesh" />
<meta name="developer" content="Md. Mohaymenul Islam">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
{% endblock meta %}
{% block body %}



<section class="uv-about-inner">
    <div class="container">
        <div class="col-xs-12 section-title">
                <h2>About Us</h2>
        </div>
        <div class="row ">
            <div class="uv-about-content overflow">
                <div class="bg-3 overflow">
                    <div class="col-sm-6 padding-o">
                        <img src="{{ about.about_image.url }}" alt="" class="img-responsive">
                    </div>
                    <div class="col-sm-6">
                        <div class="uv-about-info">
                            <h4>About Our Journey</h4>
                            <p>{{ about.our_journey }}</p>
                        </div>
                        <div class="uv-about-info">
                            <h4>Mission & Vision</h4>
                            <p>{{ about.our_history_and_passions }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--
<section class="uv-achivement">
    <div class="container">
        <div class="row section-separator">
            <div class="section-title col-xs-12">
                <h2>Our Achivements</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing aelit, sed do eiusmod tempor incididunt.</p>
            </div>
            <div class="col-xs-12">
                <div class="row">
                    <div class="uv-achivement-circle">
                        <ul>
                            <li class="col-md-3 col-sm-6">
                                <div class="row">
                                    <div class="circles col-sm-6 col-xs-6">
                                        <div class="progress progress-circle" data-progress="45"></div>
                                    </div>
                                    <div class="uv-circle-info col-sm-6 col-xs-6">
                                        <i class="fa flaticon-presentation"></i>
                                        <span>Presentation</span>
                                    </div>
                                </div>
                            </li>
                            <li class="col-md-3 col-sm-6">
                                <div class="row">
                                    <div class="circles col-sm-6 col-xs-6">
                                        <div class="progress progress-circle" data-progress="99"></div>
                                    </div>
                                    <div class="uv-circle-info col-sm-6 col-xs-6">
                                        <i class="fa flaticon-photo-camera"></i>
                                        <span>Video Lecture</span>
                                    </div>
                                </div>
                            </li>
                            <li class="col-md-3 col-sm-6">
                                <div class="row">
                                    <div class="circles col-sm-6 col-xs-6">
                                        <div class="progress progress-circle" data-progress="70"></div>
                                    </div>
                                    <div class="uv-circle-info col-sm-6 col-xs-6">
                                        <i class="fa flaticon-diploma-paper-roll"></i>
                                        <span>Alumni</span>
                                    </div>
                                </div>
                            </li>
                            <li class="col-md-3 col-sm-6">
                                <div class="row">
                                    <div class="circles col-sm-6 col-xs-6">
                                        <div class="progress progress-circle" data-progress="65"></div>
                                    </div>
                                    <div class="uv-circle-info col-sm-6 col-xs-6">
                                        <i class="fa flaticon-mortarboard"></i>
                                        <span>Certificates</span>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
-->


<section class="uv-video image-bg" style="background-image: url({% static 'takdhum/assets/images/takdhum video bg.png' %});">
    <div class="overlay">
        <div class="container">
            <div class="row section-separator">
                <h2>On site campus tour at our TAKDHUM.</h2>
                <!--<p>Lorem ipsum dolor sit amet, consectetur adipi sicing elit, sed do eiusmod tempor incididunt ut labore et.dolore magna aliquauis aute irure dolor.</p>-->
                <div class="button">
                    <a data-fancybox href="{{ info.promo_video }}"><i class="fa flaticon-play-button"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock body %}


{% block script %}
<!-- init -->
<script src="{% static "takdhum/assets/js/init.js" %}"></script>

{% endblock script %}

web/templates/takdhum/all_course.html
{% extends 'takdhum/html/base.html' %}
{% load staticfiles %}

{% block title %} {{ title }} {% endblock title %}
{% block meta %}
<!-- Meta -->
<meta charset="utf-8">
<meta name="description" content="TAKDHUM is a video-based online classroom where students develop creativity and confidence through our multi-level art instruction program. We offer video lessons that can be taken anytime, anywhere- via laptop, tablet or smart phone. Each program meets the Standards for Arts Education.
" />
<meta name="keywords" content="All Course Takdhum Online Art School in Bangladesh" />
<meta name="developer" content="Md. Mohaymenul Islam">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
{% endblock meta %}


{% block body %}
<section class="uv-subpage-heading image-bg" style="background-image: url({% static "takdhum/assets/images/takdhum-web-banner-01-01.png" %});">
    <div class="overlay">
        <div class="container">
            <div class="row">
                <div class="uv-subhead-content col-xs-12">
                    <h2>{{ tag|capfirst }} Courses </h2>
                    <span>Takdhum {{ tag }} course are given bellow</span>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="uv-pagination">
    <div class="container">
        <ul>
            <li class="active"><a href="{% url 'index' %}">Home</a></li>
            <li><a href="#">{{ tag.lower }}-courses</a></li>
        </ul>
    </div>
</div>

<section class="uv-course-archive">
    <div class="container">

        <!--Search course-->
            {% include 'takdhum/course_search.html' %}

        <!--End search course-->
        <div class="row">
            <div class="uv-courses-2">
                <div class="">
                    {% if courses %}
                    {% for c in courses %}
                     <div class="col-md-3 col-sm-6">

                        <div class="uv-courese-single-thumb uv-shadow">
                            <div class="uv-post-img">
                                <img src="{{ c.thumbnail_image.url }} " alt="" class="img-responsive">
                                <div class="uv-post-author">
                                    <span>Takdhum</span>
                                </div>
                            </div>
                            <div class="uv-course-thumb-inner">
                                <a href="{% url 'single_course' category=c.course_category.category_url course=c.course_url %}"><h4>{{ c.course_title|truncatewords:6 }}</h4></a>
                                 <!--<p><span>{{ c.course_category.category_name }}</span>  <del>$280</del></p> -->
                            </div>

                            <ul class="course-info-2">
                                <li class="course-info-2">
                                    <i class="fa fa-users"></i>
                                    <span><a href="{% url 'single_category' category=c.course_category.category_url %}">{{ c.course_category.category_name }}</a></span>
                                </li>
                                <li class="uv-course-rating">
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                        </div>
                     </div>
                    {% endfor %}
                {% else %}
                        <h4>There is no course added yet!</h4>
                {% endif %}

                </div>
            </div>
        </div>
    </div>
</section>



{% endblock body %}


{% block script %}
<!-- init -->
<script src="{% static "takdhum/assets/js/init.js" %}"></script>

{% endblock script %}

web/templates/takdhum/contact.html
{% extends 'takdhum/html/base.html' %}
{% load staticfiles %}

{% block title %} Contact {% endblock title %}
{% block meta %}
<!-- Meta -->
<meta charset="utf-8">
<meta name="description" content="{{ info.office_address }}" />
<meta name="keywords" content="Contact Us Takdhum" />
<meta name="developer" content="Md. Mohaymenul Islam">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
{% endblock meta %}

{% block body %}
<!--
<section class="uv-map">
    <div id="map">
    </div>
</section>
-->
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<section class="uv-contact">
    <div class="container">
        <div class="row section-separator">
            <div class="col-md-9 col-sm-12 col-xs-12 content-widget">
                <div class="col-xs-12 widget-title">
                    <h4>Leave a Message</h4>
                    <hr class="uv-hr">
                </div>
                <form class="single-form quate-form" data-toggle="validator" target="#" method="POST">
                    {% csrf_token %}
                    <div id="msgSubmit" class="h3 text-center hidden"></div>
                    <div class="col-md-4">
                        <input name="first_name" class="contact-name form-control" id="id_name" type="text" placeholder="First Name" required>
                        <input name="last_name" class="contact-email form-control" id="id_last_name" type="text" placeholder="Last Name" required>
                        <input name="email" class="contact-subject form-control" id="is_email" type="email" placeholder="Your Email" required>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <textarea class="contact-message form-control"  name="message" id="id_message" placeholder="Your Message" required></textarea>
                        <button type="submit" class="btn btn-fill">send message</button>
                    </div>
                </form>
            </div>
            <div class="col-md-3 col-sm-12 col-xs-12 content-widget uv-contact-details-1">
                <div class="widget-title">
                    <h4>Contact Details</h4>
                    <hr class="uv-hr">
                </div>
                <div class="contact-list">
                    <ul class="contact-details">
                        <li><i class="fa fa-link"></i> <a href="{% url 'index' %}"> {{ info.name }}</a></li>
                        <li><i class="fa fa-envelope"></i> <a href="mailto:{{ info.email }}"> {{ info.email }}</a></li>
                        <li><i class="fa fa-phone"></i> {{ info.phone_1 }}</li>
                        {% if info.phone_2 %}
                        <li><i class="fa fa-fax"></i> {{ info.phone_2 }}</li>
                        {% endif %}
                        <li><i class="fa fa-home"></i> {{ info.office_address }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock body %}


{% block script %}
<!-- init -->
<script src="{% static "takdhum/assets/js/init.js" %}"></script>

{% endblock script %}

web/templates/takdhum/course_search.html
<!--Search start-->
        <div class="uv-course-nav">

            <form action="{% url 'search' %}" method="get" class="uv-nav-form">
                <input type="text" placeholder=" Search.." name="course_title" style="width: 93%;font-size:24px;padding:5px;box-sizing:border-box;border-radius: 5px;" id="id_course_title">
                <button type="submit" style="font-size:24px;"><i class="fa fa-search"></i></button>

                <!--<ul class="row">-->
                <!--    <li class="col-md-3">-->
                <!--        <select class="select-beast">-->
                <!--            <option value="0" selected="selected">All Categories</option>-->
                <!--            {% for cat in categories %}-->
                <!--            <option class="level-0" value="23">{{ cat.category_name }}</option>-->
                <!--            {% endfor %}-->

                <!--        </select>-->
                <!--    </li>-->
                <!--    <li class="col-md-3">-->
                <!--        <select class="select-beast">-->
                <!--            <option value="0" selected="selected">All Levels</option>-->
                <!--            {% for l in level %}-->
                <!--            <option>{{ l.name }}</option>-->
                <!--            {% endfor %}-->

                <!--        </select>-->
                <!--    </li>-->
                <!--    <li class="col-md-3">-->
                <!--        <select class="select-beast">-->
                <!--            <option value="0" selected="selected">All Course Tags</option>-->
                <!--            {% for c in courses %}-->
                <!--            <option class="level-0" value="11">{{ c.course_title }}</option>-->
                <!--            {% endfor %}-->

                <!--        </select>-->
                <!--    </li>-->
                <!--    <li class="col-md-3">-->
                <!--        <input type="submit" class="btn btn-fill" value="Submit">-->
                <!--    </li>-->
                <!--</ul>-->
            </form>
        </div>
        <!--search end-->

web/templates/takdhum/faq.html
{% extends 'takdhum/html/base.html' %}
{% load staticfiles %}

{% block title %} FAQ {% endblock title %}

{% block body %}


<section class="uv-topics">
    <div class="container">
        <div class="row section-separator">
            <div class="col-xs-12 section-title">
                <h2>Frequently Asked Questions</h2>
            </div>
            <div class="col-xs-12">
                <div id="integration-list" class="uv-accordinaton">
                    <ul>
                        {% for f in faq %}
                        <li>
                            <a class="uv-accordinaton-list">
                                <div class="uv-right-arrow">+</div>
                                <h2>{{ f.question }}</h2>
                            </a>
                            <div class="uv-accordition-detail">
                                <p>{{ f.answer }}</p>
                            </div>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock body %}


{% block script %}
<!-- init -->
<script src="{% static "takdhum/assets/js/init.js" %}"></script>

{% endblock script %}