takdhum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tdlogin/', admin.site.urls),
    path('', include('web.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quizs.urls')),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('course/<category>', views.courseCategory, name='single_category'),
    path('course/<category>/<level>', views.drawing_course, name='drawing_course'),
    path('<category>/course/<course>', views.course, name='single_course'),
    path('all-courses', views.all_course, name='all_course'),
    path('popular-courses', views.popular_course, name='popular_course'),
    path('resent-courses', views.recent_course, name='recent_course'),
    path('event/<event_id>', views.event, name='single_event_page'),
    path('contact', views.contact, name='contact_page'),
    path('about-us', views.about_us, name='about_page'),
    path('faq', views.faq, name='faq_page'),
    path('login', views.get_login, name='get_login'),
    path('logout', views.get_logout, name='logout'),
    path('profile/<username>/', views.get_user_profile, name='user_profile'),
    path('sign-up', views.signup, name='sign-up'),
    path('user-message', views.user_message, name='user_message'),
    # path('activate/<uidb64>/<token>', views.activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
     views.activate, name='activate'),
    # path('profile/<slug:slug>/', views.ProfilePage.as_view(), name='user_profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('events_list', views.EventListView.as_view(), name='event_list'),
    path('subcriber', views.subscriber, name='subcriber'),
    path('search', views.search, name='search'),
    path('<user>/my-course/', views.my_course, name='my_course'),
    # path('<user>/my-course/', views.TakenCourseList.as_view(), name='my_course')
    path('<user>/delete_course/<int:pk>/', views.taken_course_delete, name='delete_course'),
    # path('taken-quiz/<int:pk>/', views.take_quiz, name='take-quiz'),
    path('<course>/question-list/', views.question_list, name='question-list'),
    path('question/', views.take_quiz, name='question'),
    path('student-answer/<username>/', views.student_answer, name='student-answer'),
    path('mcq/<int:question_id>/', views.score, name='vote'),
    path('all-answer/', views.AllAnswer.as_view(), name="all-answer"),
    path('quize-datails/', views.quize_details, name='quize-details'),
    path('vedio_link/', views.vedio_link, name='vedio_link'),
    path('<category>/<course>/<video>/', views.single_video, name='single_vedio'),
    path('<course_watch>/watch_vedio/', views.watch_vedio, name='watch_vedio'),
    # path('api/status/', views.api_status, name='api-status'),
]

web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    profile_picture = models.ImageField(upload_to='Profile_picture/', null=True, blank=True)
    father_name = models.CharField(max_length=255, blank=True, null=True)
    mother_name = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.IntegerField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    institute = models.CharField(max_length=255, blank=True, null=True)
    facebook = models.CharField(max_length=255, blank=True, null=True)
    twitter = models.CharField(max_length=255, blank=True, null=True)
    youtube = models.CharField(max_length=255, blank=True, null=True)
    linkedin = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    def get_absulete_url(self):
        return reverse('user_profile', args=[str(self.slug)])


@receiver(post_save, sender=User)
def create_profile_for_user(sender, instance=None, created=False, **kwargs):
    if created:
        Profile.objects.get_or_create(user=instance)


class CourseCategory(models.Model):
    category_name = models.CharField(max_length=50)
    category_url = models.CharField(max_length=50)
    thumbnail_image = models.ImageField(upload_to='Course_Category', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.category_name


class CourseLevel(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Course(models.Model):
    course_title = models.CharField(max_length=150)
    course_url = models.CharField(max_length=150)
    thumbnail_image = models.ImageField(upload_to='Courses')
    course_category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)
    course_level = models.ForeignKey(CourseLevel, null=True, blank=True, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    def __str__(self):
        return self.course_title


class TakenCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='taken_courses')
    taken_course_title = models.CharField(max_length=255, null=True)
    taken_course_url = models.CharField(max_length=255, null=True)
    taken_course_image = models.ImageField(upload_to='User/TakenCourses', null=True)
    taken_course_category = models.CharField(max_length=255, null=True)
    taken_category_url = models.CharField(max_length=255, null=True)
    view = models.PositiveIntegerField(blank=True, null=True)
    taken_time = models.DateTimeField(auto_now=True)
    last_visited = models.DateTimeField()

    class Meta:
        unique_together = (('user', 'taken_course_url'),)

    def get_absolute_url(self):
        return reverse('my_course', kwargs={'pk': self.pk})

    def __str__(self):
        return self.taken_course_url


class SingleVideo(models.Model):
    video_title = models.CharField(max_length=150)
    video_url = models.CharField(max_length=150)
    video_link = models.URLField()
    course_name = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_public = models.BooleanField(default=False)
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.video_title


class AboutUs(models.Model):
    our_journey = models.TextField()
    our_history_and_passions = models.TextField(blank=True, null=True)
    about_image = models.ImageField(upload_to='About us')

    def __str__(self):
        return self.our_journey


class Basic_info(models.Model):
    name = models.CharField(max_length=100)
    slogan = models.CharField(max_length=200)
    logo = models.ImageField(upload_to='About us')
    phone_1 = models.CharField(max_length=15)
    phone_2 = models.CharField(max_length=15, null=True, blank=True)
    email = models.EmailField()
    office_address = models.TextField()
    promo_video = models.URLField(blank=True, null=True)
    google_map_link = models.URLField(null=True, blank=True)
    facebook_link = models.URLField(null=True, blank=True)
    google_plus_link = models.URLField(null=True, blank=True)
    youtube_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Slider(models.Model):
    small_text = models.CharField(max_length=100, null=True, blank=True)
    big_text = models.CharField(max_length=100)
    paragraph = models.CharField(max_length=250)
    slide_image = models.ImageField(upload_to='Slider_Image')

    def __str__(self):
        return self.big_text


class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    date_and_time = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.question


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.CharField(max_length=3)
    month = models.CharField(max_length=10)
    start_and_end_time = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    image = models.ImageField(upload_to='Events')
    gallery_image1 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image2 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image3 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image4 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image5 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image6 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image7 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image8 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image9 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image10 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image11 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    gallery_image12 = models.FileField(blank=True, null=True, upload_to='Gallery/events')
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    Image = models.ImageField(upload_to='Projects')
    upload_time = models.DateTimeField(auto_now_add=True, auto_now=False)
    update_time = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    person_name = models.CharField(max_length=100)
    person_designation = models.CharField(max_length=100)
    person_comment = models.TextField()
    person_image = models.ImageField(upload_to='Testimonial')
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.person_name


class UserMessage(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.first_name + self.last_name


class Subcribe(models.Model):
    subcriber_email = models.EmailField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subcriber_email


class Question(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    question = models.CharField('Question', max_length=400)
    question_file = models.FileField('Question', upload_to='Question-file', blank=True, null=True)
    option1 = models.CharField(max_length=50, blank=True, null=True)
    option2 = models.CharField(max_length=50, blank=True, null=True)
    option3 = models.CharField(max_length=50, blank=True, null=True)
    option4 = models.CharField(max_length=50, blank=True, null=True)
    correct_answer = models.CharField(max_length=25, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.question


class StudentAnswer(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank=True, null=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    answer_file = models.FileField(upload_to='Student-answer', blank=True, null=True)
    answer_text = models.CharField(max_length=255, blank=True, null=True)
    counter = models.PositiveIntegerField(blank=True, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    is_pass = models.BooleanField(default=False)

    def __str__(self):
        return self.student.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='taken_quizzes')
    date = models.DateTimeField(auto_now_add=True)


class WatchVideo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(CourseCategory, on_delete=models.CASCADE)

web/templates/takdhum/html/footer.html
{% load staticfiles %}
<!--
        |========================
        |  footer
        |========================
        -->
<footer class="uv-footer footer-bg section-separator">
    <div class="container">
        <div class="row">

            <div class="col-md-3 col-sm-6 wow fadeInUp" data-wow-delay="0.2s">
                <div class="footer-item">

                    <h6>Contact Us</h6>
                    {% if info.office_address %}
                        <address>{{ info.office_address }}</address>
                    {% else %}
                        <address>Hourse 540/1, Road-8, West Nakhalpara, Dhaka, Bangladesh</address>
                    {% endif %}

                    {% comment %}
                            <ul>
                                <li><a href="#"><i class="fa fa-phone"></i>{{ info.phone_1 }}</a></li>
                                {% if info.phone_2 %}
                                <li><a href="#"><i class="fa fa-phone"></i>{{ info.phone_2 }}</a></li>
                                {% endif %}
                                <li><a href="#"><i class="fa fa-envelope-o"></i>{{ info.email }}</a></li>
                            </ul>


                            <ul class="social">
                                <li><a href="{{ info.facebook_link }}" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="{{ info.google_plus_link }}" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="{{ info.youtube_link }}" target="_blank"><i class="fa fa-youtube"></i></a></li>
                            </ul>
                            {% endcomment %}
                </div>
            </div>

            <div class="col-md-3 col-sm-6 wow fadeInUp" data-wow-delay="0.4s">
                <div class="footer-item uv-program">
                    <ul>
                        {% if info.phone_1 %}
                            <li><a href="#"><i class="fa fa-phone"></i>{{ info.phone_1 }}</a></li>
                            {% if info.phone_2 %}
                                <li><a href="#"><i class="fa fa-phone"></i>{{ info.phone_2 }}</a></li>
                            {% endif %}
                            <li><a href="#"><i class="fa fa-envelope-o"></i>{{ info.email }}</a></li>
                        {% else %}
                            <li><a href="#"><i class="fa fa-phone"></i>+8801714016515</a></li>
                            <li><a href="#"><i class="fa fa-envelope-o"></i>info@takdhum.com</a></li>
                        {% endif %}
                    </ul>

                    <ul class="social">

                        <li><a href="{{ info.facebook_link }}" target="_blank"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="{{ info.google_plus_link }}" target="_blank"><i class="fa fa-google-plus"></i></a>
                        </li>
                        <li><a href="{{ info.youtube_link }}" target="_blank"><i class="fa fa-youtube"></i></a></li>
                    </ul>

                    {% comment %}
                            <h6>Our Company</h6>
                            <ul>
                                <li><a href="{% url 'about_page' %}">About Us</a></li>
                                <li><a href="#">FAQ</a></li>
                                <li><a href="{% url 'all_course' %}">Courses</a></li>
                                <li><a href="#">Our Mission</a></li>
                                <li><a href="#">Our History</a></li>
                                <li><a href="#">Trams & Condition</a></li>
                            </ul>
                            {% endcomment %}
                </div>
            </div>
            <div class="col-md-3 col-sm-6 wow fadeInUp" data-wow-delay="0.6s">
                <div class="footer-item">
                    <h6>Newsletter</h6>
                    <p>Enter your email and we'll send you more information of courses and scholarship.</p>

                    {% comment %}
                            <h6>Our Courses</h6>
                            <ul>
                                {% for c in categories %}
                                    <li><a href="{% url 'single_category' category=c.category_url %}">{{ c.category_name }} Courses</a></li>
                                {% endfor %}
                                <li><a href="{% url 'all_course' %}">All Courses</a></li>
                                <li><a href="{% url 'popular_course' %}">Popular Courses</a></li>
                                <li><a href="{% url 'recent_course' %}">Resent Courses</a></li>
                            </ul>
                            {% endcomment %}
                </div>
            </div>
            <div class="col-md-3 col-sm-6 wow fadeInUp" data-wow-delay="0.8s">
                <div class="footer-item">

                    <form class="uv-form footer-form" method="post" action="{% url 'subcriber' %}">
                        {% csrf_token %}
                        <div class="form-group relative">
                            <div class="relative">
                                <input type="text" class="form-control" name="subcriber_email" id="id_subcriber_email"
                                       placeholder="Email Address" required>
                            </div>
                        </div>
                        <div class="footer-subs-btn">
                            <button type="submit" class="btn btn-base" value="subscribe">Subcribe</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <hr class="f-hr">
        <div class="row">
            <div class="uv-copyright center wow fadeInUp" data-wow-delay="0.5s">
                <p>Takdhum © Copyright 2018. All rights reserved.
                    <!--Developed by <a href="http://www.denarycomputing.com/" target="_blank">Denary Computing Limited</a> -->
                </p>
            </div>
        </div>
    </div>
</footer>

web/templates/takdhum/html/header.html
{% load staticfiles %}
<!--
|========================
|  HEADER
|========================
-->
<header class="xt-header">
    <div class="xt-header-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 uv-header-contact">
                    {% if info.phone_1 %}
                        <a href="#"> <i class="fa fa-phone"></i>{{ info.phone_1 }}</a>
                    {% else %}
                        <a href="#"> <i class="fa fa-phone"></i>+8801714016515</a>
                    {% endif %}
                    {% if info.email %}
                        <a href="#"> <i class="fa fa-envelope-o"></i>{{ info.email }}</a>
                    {% else %}
                        <a href="#"> <i class="fa fa-envelope-o"></i>info@takdhum.com</a>
                    {% endif %}
                </div>
                <div class="col-sm-6 uv-header-user">
                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'get_login' %}"><i class="fa fa-lock"></i>login/register</a>
                    {% else %}
                        <a href="{% url 'my_course' user=request.user %}"><i class="fa fa-book"></i>Resume course</a>
                    {% endif %}
                    <div class="xt-header-search">
                        <div id="besocial-header-right" class="">
                            <i class="fa fa-remove"></i>
                            <i class="fa fa-search"></i>
                        </div>
                        <div id="besocial-search-bar" class="">
                            <form class="besocial-topbar-searchbox" action="{% url 'search' %}" method="get">
                                <input type="text" class="besocial-topbar-searchtext" placeholder="Search..."
                                       name="course_title" id="id_course_title">
                                <input type="submit" class="fa-input" name="submit" value="Go">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="xt-main-nav">
        <nav class="navbar nav-scroll home-1">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="uv-logo">
                            {% if info.logo.url %}
                                <a href="{% url 'index' %}">
                                    <img src="{{ info.logo.url }}" alt="" class="img-responsive">
                                </a>
                            {% else %}
                                <a href="{% url 'index' %}">
                                    <img src="{% static 'takdhum/assets/images/univ-logo.png' %}" alt=""
                                         class="img-responsive">
                                </a>
                            {% endif %}


                        </div>
                    </div>
                    <div class="col-sm-8 pull-right">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                    data-action="#js-navbar-menu" aria-expanded="false">
                                <span aria-hidden="true" class="icon"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="js-navbar-menu">
                            <ul class="nav navbar-nav ep-mobile-menu" id="navbar-nav">
                                <li><a href="{% url 'index' %}">Home</a></li>
                                <li class="dropdown xt-drop-nav">
                                    {% if categories %}
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                                           data-animations="fadeInDown fadeInDown fadeInDown">
                                            Courses
                                        </a>
                                        <ul class="dropdown-menu">
                                            {% for c in categories %}
                                                <li>
                                                    <a href="{% url 'single_category' category=c.category_url %}">{{ c.category_name }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    {% else %}
                                        <li><a href="{% url 'all_course' %}">Courses</a></li>
                                    {% endif %}

                                </li>


                                <!--
                                <li class="dropdown xt-drop-nav">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-animations="fadeInDown fadeInDown fadeInDown">
                                        Blog
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="blog.html">Blog Page</a></li>
                                        <li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li>

                                <li class="dropdown xt-drop-nav">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-animations="fadeInDown fadeInDown fadeInDown">
                                        Features
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="about.html">About</a></li>
                                        <li><a href="services.html">FAQ</a></li>
                                        <li><a href="not-found.html">404</a></li>
                                    </ul>
                                </li>
                                -->
                                <!--<li><a href="#">FAQ</a></li>-->
                                <!--<li><a href="{% url 'faq_page' %}">FAQ</a></li>-->
                                <li><a href="{% url 'about_page' %}">About Us</a></li>
                                <li><a href="{% url 'contact_page' %}">Contact</a></li>

                                {% if request.user.is_authenticated %}
                                    <li><a href="#"></a></li>

                                    <li class="dropdown xt-drop-nav">

                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                                           data-animations="fadeInDown fadeInDown fadeInDown">
                                            {{ request.user }}
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a href="{% url 'user_profile' username=user.username %}">Profile</a></li>
                                            <li><a href="{% url 'update_profile' %}">Profile Settings</a></li>
{#                                            <!--<li><a href="{% url 'user_profile' slug=request.user %}">Profile</a></li>-->#}
{#                                            <!--<li><a href="#">Classes</a></li>-->#}
                                            <li><a href="{% url 'my_course' user=request.user %}">Courses</a></li>
                                            <li><a href="{% url 'student-answer' username=request.user %}"><i class="fa fa-calendar"></i>My taken quiz</a></li>
                                            <!--<li><a href="#">Favorite Course</a></li>
                                            <li><a href="#">Privacy Setting</a></li>
                                            <li><a href="#">Profile Setting</a></li>-->
                                            <li><a href="{% url 'password_change' %}">Change Password</a></li>
                                            <li><a href="{% url 'logout' %}">Logout</a></li>
                                        </ul>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav><!-- /.navbar -->
    </div>


    <!-- Mobile Menu-->
    <div class="menu-spacing visible-xs nav-scroll">
        <div class="mobile-menu-area visible-xs visible-sm">
            <div class="mobile-menu">
                <nav id="mobile-menu-active">
                    <ul class="main">
                        <li class="active"><a class="main-a" href="{% url 'index' %}">Home</a>

                        </li>
                        <li><a class="main-a" href="#">Courses</a>
                            <ul>
                                {% for c in categories %}
                                    <li>
                                        <a href="{% url 'single_category' category=c.category_url %}">{{ c.category_name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <!--
                        <li><a class="main-a" href="#">Features</a>
                            <ul>
                                <li><a href="not-found.html">404</a></li>
                                <li><a href="login-reg.html">Login & Registration</a></li>
                                <li><a href="teacher-details.html">Team Details</a></li>
                                <li><a href="classes.html">Classes</a></li>
                                <li><a href="about.html">About</a></li>
                                <li><a href="services.html">Service</a></li>
                            </ul>
                        </li>


                        <li><a class="main-a" href="#">Blog</a>
                            <ul>
                                <li><a href="blog.html">Blog Page</a></li>
                                <li><a href="blog-single.html">Blog Single</a></li>
                            </ul>
                        </li>
                        -->
                        <!--<li><a class="main-a" href="#">FAQ</a></li>-->
                        <!--<li><a class="main-a" href="{% url 'faq_page' %}">FAQ</a></li>-->
                        <li><a class="main-a" href="{% url 'about_page' %}">About Us</a></li>
                        <li><a class="main-a" href="{% url 'contact_page' %}">Contact</a></li>

                        {% if request.user.is_authenticated %}
                            <li><a class="main-a" href="#">{{ request.user }}</a>
                                <ul>
                                    <li><a href="{% url 'user_profile' username=user.username %}">Profile</a></li>
                                    <li><a href="{% url 'update_profile' %}">Profile Settings</a></li>
                                    <!--<li><a href="#">Classes</a></li>-->
                                    <li><a href="{% url 'my_course' user=request.user %}">Courses</a></li>
                                    <li><a href="{% url 'student-answer' username=request.user %}"><i class="fa fa-calendar"></i>My taken quiz</a></li>
                                    <!--<li><a href="#">Favorite Course</a></li>
                                    <li><a href="#">Privacy Setting</a></li>
                                    <li><a href="#">Profile Setting</a></li>-->
                                    <li><a href="{% url 'password_change' %}">Change Password</a></li>
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a class="main-a" href="{% url 'get_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>